steps:
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    args:
      - gcloud
      - functions
      - deploy
      - saveQuoteToDatastore
      - '--region=us-central1'
      - '--source=functions/saveQuoteToDatastore/'
      - '--trigger-topic=quote-data'